---
# tasks file for packages
#- name: Install prerequisites packages
#  apt:
#    name: packages
#    state: present
#    update_cache: yes
- name: Install prerequisites packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - "{{ software_packages }}"